name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Set Vars
      run:  echo "imagename_pydantic-mcp-python=ghcr.io/semaverse/pydantic-mcp-python-run:basic-$(date +%Y-%m-%d)" >> $GITHUB_ENV       

    - name: Build the Docker image pydantic-mcp-python
      run: | 
        docker build . --file python/pydantic-mcp-python-run/basic/Dockerfile --tag ${{ env.imagename_pydantic-mcp-python }}
        docker push ${{ env.imagename_pydantic-mcp-python }}

