name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  tag: naive-$(date +%s)
  imagename: ghcr.io/semaverse/pydantic-mcp-run-python:{{ env.tag }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build the Docker image
      run: | 
        docker build . --file pydantic-mcp-python-run/naive/Dockerfile --tag ${{ env.imagename }}
        docker push ${{ env.imagename }}

